### ISSUE TITLE
Research topic: DOCK Blaster

### ISSUE THREAD

**Issue by jir322** [docking-org/IrwinLab#20]
Lowering the barriers to entry for molecular docking

Molecular docking is the most pragmatic approach to use protein structures for ligand discovery. Notwithstanding numerous successes, the technique remains difficult to use for novices and is tricky even for experts. DOCK Blaster is our attempt to lower the barriers to using molecular docking.

In 2018 we broke ground on a new version of DOCK Blaster, Blaster18, which aims to address weaknesses in our first implementation, Blaster9. 

Blaster18 is powered by UCSF DOCK 3.7 and ZINC15. 

We are currently testing Blaster18. In the meantime, the previous versions are:

* DOCK Blaster - blaster.docking.org - a free web portal for non-covalent molecular docking.

* DOCKovalent - covalent.docking.org - a free covalent docking server.

* Metabolite docking - metabolite.docking.org - a molecular docking service focused on metabolite docking for protein function discovery.

**Comment by khtang17** [comment]
Modified
