### ISSUE TITLE
Research Topic: ZINC15 (notice this is adapted from ZINC12, updated)

### ISSUE THREAD

**Issue by jir322** [docking-org/IrwinLab#21]
Ligand based tools

We develop and maintain ZINC, a database of commercially available and annotated compounds for virtual screening, ligand discovery, and systems pharmacology.

ZINC allows you to answer questions such as:

* What compounds can I buy that are similar to my compound? (ABC or Analog By Catalog)

* What compounds can I buy that are active against my target? (intersecting annotated and purchasable chemical space)

* What are the most similar metabolites, drugs, or other bioactives to my compound? (bioactivity inference by molecular similarity)

* What building blocks can I buy to do chemistry?

**Comment by jir322** [comment]
As I have been working on this text, I have rapidly realized that I need to do a lot of work. Let's get these few changes made, which will already be better than what is there now.  Then I will improve on that. thank you

**Comment by khtang17** [comment]
Changes added. Thanks John!!
